title "In Class Problem Handout";
title2 "Problem 1";
data orion.increase1; 
	set orion.staff; 
	Increase = (Salary*0.10);
	NewSalary = SUM(Salary , Increase);
	BdayQtr = qtr(Birth_Date);
	keep Employee_ID Salary Birth_Date  Increase NewSalary BdayQtr;
	label	Employee_ID = 'Employee ID'
			Salary = 'Employee Salary'
			Birth_Date = 'Birth Date'
			BdayQtr = 'Bday Qtr';
run;
proc print data=orion.increase1;
run;
title2 "Problem 2";
data work.bonus;
	set orion.sales;
	if Country='US' then Bonus=500;
		else Bonus=300;
run;
proc print data=work.bonus;
	var First_Name Last_Name Country Bonus;
run;
Proc Freq Data=bonus;
	Tables Country;
Run;
Proc Print data = bonus(where=(bonus=300));
	Var Country Salary;
run;
title2 "Problem 3";
Data work.region;
	set orion.supplier;
	length Region $ 17;
	if in ('CA','US') then do;
		Discount=0.10;
		DiscountType="Required";
		Region="North America";
	end;
	Else do;
		Discount=0.05;
		DiscountType="Optional";
		Region="Not North America";
	end;
	Keep Supplier_name Country Discount DiscountType Region;
run;
proc print data=work.region;
run;
proc freq data=work.region;
	table Country;
run;
title2 "Problem 4";
data work.season;
	set orion.customer_dim;
	qtr = qtr(Customer_BirthDate);
	if qtr=1 then Promo='Winter';
		else if qtr=2 then Promo='Spring';
		else if qtr=3 then Promo='Summer';
		else if qtr=4 then Promo='Fall';
	if Customer_Age is between 18 and 25 then Promo2='YA';
		else if Customer_Age >75 then Promo2='Senior';

